
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FSBI10
 */
public class Zurueckpielen extends javax.swing.JFrame {
    private String strZipfile;

    /**
     * Creates new form Zurueckpielen
     */
    public Zurueckpielen() {
        strZipfile = "";
        initComponents();
        
    }

    public void setZipfile(String strZipfile) {
        this.strZipfile = strZipfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnZurueckpielen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList();
        btnAllesAnwaehlen = new javax.swing.JButton();
        btnAllesAbwaehlen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnZurueckpielen.setText("Entpacken");
        btnZurueckpielen.setEnabled(false);
        btnZurueckpielen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZurueckpielenActionPerformed(evt);
            }
        });

        listFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFiles);

        btnAllesAnwaehlen.setText("Alles anwählen");
        btnAllesAnwaehlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllesAnwaehlenActionPerformed(evt);
            }
        });

        btnAllesAbwaehlen.setText("Alles abwählen");
        btnAllesAbwaehlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllesAbwaehlenActionPerformed(evt);
            }
        });

        jButton1.setText("Abbrechen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnZurueckpielen)
                .addGap(27, 27, 27)
                .addComponent(btnAllesAnwaehlen)
                .addGap(18, 18, 18)
                .addComponent(btnAllesAbwaehlen)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZurueckpielen)
                    .addComponent(btnAllesAnwaehlen)
                    .addComponent(btnAllesAbwaehlen)
                    .addComponent(jButton1))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZurueckpielenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZurueckpielenActionPerformed
        Zippen zip = new Zippen();
        String directory;
        
        try {
            // Ziel wälen
            JFileChooser destination = new JFileChooser();
            destination.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            destination.setDialogTitle("Zielauswahl");
            destination.showOpenDialog(null);
            directory = destination.getSelectedFile().getPath();
            
            if (!directory.isEmpty())
            {
                // entpacken.extractArchive();
                List<String> listeob = listFiles.getSelectedValuesList();
                listeob.toArray(new String[listeob.size()]);
                zip.extractArchive(strZipfile, listeob, directory);
            }
        } catch(Exception e) {
            System.out.println("Fehler beim entpacken!");
        }
    }//GEN-LAST:event_btnZurueckpielenActionPerformed

    private void listFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFilesValueChanged
        if (listFiles.getSelectedIndex() == -1 )
        {
            btnZurueckpielen.setEnabled(false);
        } else {
            btnZurueckpielen.setEnabled(true);
        }
    }//GEN-LAST:event_listFilesValueChanged

    private void btnAllesAnwaehlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllesAnwaehlenActionPerformed
        listFiles.setSelectionInterval(0, listFiles.getModel().getSize()-1);
    }//GEN-LAST:event_btnAllesAnwaehlenActionPerformed

    private void btnAllesAbwaehlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllesAbwaehlenActionPerformed
        listFiles.clearSelection();
    }//GEN-LAST:event_btnAllesAbwaehlenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // JFrame zentriert zum Parent positionieren:
        setLocationRelativeTo(getParent());
    }//GEN-LAST:event_formWindowOpened

    public void ZeigeZipInhalt()
    {
        Zippen zip = new Zippen();
        
        try {
            String[] str = zip.leseZipinhalt(strZipfile);

            DefaultListModel model = new DefaultListModel();
            
            
            for (int x=0; x<str.length; x++)
            {
                model.addElement(str[x]);
            }
                        
            listFiles.setModel(model);
        } catch(Exception e) {
            System.out.println("Fehler beim entpacken!");
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllesAbwaehlen;
    private javax.swing.JButton btnAllesAnwaehlen;
    private javax.swing.JButton btnZurueckpielen;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFiles;
    // End of variables declaration//GEN-END:variables
}
