
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FSBI10
 */
public class Zurueckpielen extends javax.swing.JFrame {
    private String strZipfile;

    /**
     * Creates new form Zurueckpielen
     */
    public Zurueckpielen() {
        strZipfile = "";
        initComponents();
        
    }

    public void setZipfile(String strZipfile) {
        this.strZipfile = strZipfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnZurueckpielen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnZurueckpielen.setText("entpacken");
        btnZurueckpielen.setEnabled(false);
        btnZurueckpielen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZurueckpielenActionPerformed(evt);
            }
        });

        listFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFiles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnZurueckpielen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnZurueckpielen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZurueckpielenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZurueckpielenActionPerformed
        Zippen zip = new Zippen();
        String directory;
        
        try {
            // Ziel wälen
            JFileChooser destination = new JFileChooser();
            destination.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            destination.setDialogTitle("Zielauswahl");
            destination.showOpenDialog(null);
            directory = destination.getSelectedFile().getPath();
            
            if (!directory.isEmpty())
            {
                // entpacken.extractArchive();
                List<String> listeob = listFiles.getSelectedValuesList();
                listeob.toArray(new String[listeob.size()]);
                zip.extractArchive(strZipfile, listeob, directory);
            }
        } catch(Exception e) {
            System.out.println("Fehler beim entpacken!");
        }
    }//GEN-LAST:event_btnZurueckpielenActionPerformed

    private void listFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFilesValueChanged
        if (listFiles.getSelectedIndex() == -1 )
        {
            btnZurueckpielen.setEnabled(false);
        } else {
            btnZurueckpielen.setEnabled(true);
        }
    }//GEN-LAST:event_listFilesValueChanged

    public void ZeigeZipInhalt()
    {
        Zippen zip = new Zippen();
        
        try {
            String[] str = zip.leseZipinhalt(strZipfile);

            DefaultListModel model = new DefaultListModel();
            
            
            for (int x=0; x<str.length; x++)
            {
                model.addElement(str[x]);
            }
                        
            listFiles.setModel(model);
        } catch(Exception e) {
            System.out.println("Fehler beim entpacken!");
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZurueckpielen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFiles;
    // End of variables declaration//GEN-END:variables
}
